name: base
description: Module description


core:
  package:
    - base
    - base-devel

    - linux
    - linux-headers
    - linux-zen
    - linux-zen-headers

    - linux-firmware
    - efibootmgr
    - sudo

graphic:
  package:
    - mesa
    - mesa-utils
    - vulkan-mesa-implicit-layers
    - libva
    - libva-utils

intel:
  package:
    - intel-ucode

    - vulkan-intel
    - intel-media-driver
    - libva-intel-driver

    # - intel-gpu-tools

    # - vlc-plugin-quicksync

amd:
  package:
    - vulkan-radeon

    # - radeontop
    # - amdgpu_top

file:
  package:
    - ntfs-3g
    - udisks2
    - udiskie
    # - udisk2-btrfs
    # - btrfs-progs
    # - udisks2-lvm2
    # - lvm2
    # - gvfs
  system-unit:
    - udisks2
  user-unit:
    - udiskie.service

sound:
  package:
    - pipewire
    - pipewire-alsa
    - pipewire-pulse
    - wireplumber

network:
  package:
    # - ufw
    # - gufw
    - openssh
    # - iwd
    - networkmanager
  system-unit:
    - NetworkManager.service
    - sshd.service

power:
  package:
    # - cpupower
    - preload
    - thermald
    - irqbalance
    - auto-cpufreq
    - ananicy-cpp
  system-unit:
    # - cpupower.service
    - thermald.service
    - irqbalance.service
    - auto-cpufreq.service
    - preload.service
    - ananicy-cpp.service


other:
  package:
    - reflector

units:
  - fstrim.timer
  - reflector.timer


# pre_install_hook:
# post_install_hook: scripts/my-setup.sh
# pacman -Ql openssh | grep systemd/system
