name: base
description: Module description

core:
  package:
    - base
    - base-devel

    - linux
    - linux-headers
    - linux-zen
    - linux-zen-headers

    - linux-firmware
    - efibootmgr
    - sudo

graphic:
  package:
    - mesa
    - mesa-utils
    - vulkan-mesa-implicit-layers

    - libva
    - libva-utils

intel:
  package:
    - intel-ucode

    - vulkan-intel
    - intel-media-driver
    - libva-intel-driver

    # - intel-gpu-tools

    # - vlc-plugin-quicksync

amd:
  package:
    - vulkan-radeon

    # - radeontop
    # - amdgpu_top

file-system:
  package:
    - ntfs-3g
    - udisks2
    - udiskie

    - gvfs
    - gvfs-mtp
  system-unit:
    - udisks2

sound:
  package:
    - pipewire
    - wireplumber
    - pipewire-alsa
    - pipewire-pulse
    - pipewire-audio
    - alsa-utils

    - easyeffects
    - qpwgraph
    - pavucontrol
  system-unit:
    - pipewire
    - pipewire-pulse
    - wireplumber

network:
  package:
    # - ufw
    # - gufw
    - openssh
    # - iwd
    - networkmanager
  system-unit:
    - NetworkManager
    - sshd

power:
  package:
    # - cpupower
    - preload
    - thermald
    - irqbalance
    - auto-cpufreq
    - ananicy-cpp
  system-unit:
    # - iwd
    # - cpupower
    - thermald
    - irqbalance
    - auto-cpufreq
    - preload
    - ananicy-cpp

other:
  package:
    - reflector
  system-unit:
    - fstrim.timer
    - reflector.timer


# pre_install_hook:
# post_install_hook: scripts/my-setup.sh
# pacman -Ql openssh | grep systemd/system
