[ColorScheme]
active_colors=#1c1c14, #fcfaec, #f1eee1, #787869, #e5e3d2, #c9c7b6, #1c1c14, #ffffff, #1c1c14, #fcfaec, #fcfaec, #000000, #5e621b, #ffffff, #5f6044, #5f6044, #f7f4e7, #fcfaec, #fcfaec, #47473b, #47473b
disabled_colors=#47473b, #e5e3d2, #f1eee1, #787869, #e5e3d2, #c9c7b6, #47473b, #47473b, #47473b, #e5e3d2, #e5e3d2, #000000, #e5e3d2, #47473b, #47473b, #47473b, #e5e3d2, #e5e3d2, #e5e3d2, #47473b, #47473b
inactive_colors=#47473b, #fcfaec, #f1eee1, #787869, #e5e3d2, #c9c7b6, #47473b, #47473b, #47473b, #fcfaec, #fcfaec, #000000, #5f6044, #ffffff, #5f6044, #5f6044, #f7f4e7, #fcfaec, #fcfaec, #47473b, #47473b

[ColorEffects:Disabled]
Color=71,71,59
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=120,120,105
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=241,238,225
BackgroundNormal=252,250,236
DecorationFocus=94,98,27
DecorationHover=94,98,27
ForegroundActive=94,98,27
ForegroundInactive=71,71,59
ForegroundLink=60,102,89
ForegroundNegative=186,26,26
ForegroundNeutral=95,96,68
ForegroundNormal=28,28,20
ForegroundPositive=60,102,89
ForegroundVisited=95,96,68

[Colors:Complementary]
BackgroundAlternate=241,238,225
BackgroundNormal=252,250,236
DecorationFocus=94,98,27
DecorationHover=94,98,27
ForegroundActive=94,98,27
ForegroundInactive=71,71,59
ForegroundLink=60,102,89
ForegroundNegative=186,26,26
ForegroundNeutral=95,96,68
ForegroundNormal=28,28,20
ForegroundPositive=60,102,89
ForegroundVisited=95,96,68

[Colors:Header]
BackgroundAlternate=252,250,236
BackgroundNormal=252,250,236
DecorationFocus=94,98,27
DecorationHover=94,98,27
ForegroundActive=94,98,27
ForegroundInactive=71,71,59
ForegroundLink=60,102,89
ForegroundNegative=186,26,26
ForegroundNeutral=95,96,68
ForegroundNormal=28,28,20
ForegroundPositive=60,102,89
ForegroundVisited=95,96,68

[Colors:Header][Inactive]
BackgroundAlternate=252,250,236
BackgroundNormal=252,250,236
DecorationFocus=94,98,27
DecorationHover=94,98,27
ForegroundActive=94,98,27
ForegroundInactive=71,71,59
ForegroundLink=60,102,89
ForegroundNegative=186,26,26
ForegroundNeutral=95,96,68
ForegroundNormal=28,28,20
ForegroundPositive=60,102,89
ForegroundVisited=95,96,68

[Colors:Selection]
BackgroundAlternate=228,232,146
BackgroundNormal=94,98,27
DecorationFocus=94,98,27
DecorationHover=94,98,27
ForegroundActive=255,255,255
ForegroundInactive=71,71,59
ForegroundLink=60,102,89
ForegroundNegative=186,26,26
ForegroundNeutral=95,96,68
ForegroundNormal=255,255,255
ForegroundPositive=60,102,89
ForegroundVisited=95,96,68

[Colors:Tooltip]
BackgroundAlternate=252,250,236
BackgroundNormal=252,250,236
DecorationFocus=94,98,27
DecorationHover=94,98,27
ForegroundActive=94,98,27
ForegroundInactive=71,71,59
ForegroundLink=60,102,89
ForegroundNegative=186,26,26
ForegroundNeutral=95,96,68
ForegroundNormal=28,28,20
ForegroundPositive=60,102,89
ForegroundVisited=95,96,68

[Colors:View]
BackgroundAlternate=247,244,231
BackgroundNormal=252,250,236
DecorationFocus=94,98,27
DecorationHover=94,98,27
ForegroundActive=94,98,27
ForegroundInactive=71,71,59
ForegroundLink=60,102,89
ForegroundNegative=186,26,26
ForegroundNeutral=95,96,68
ForegroundNormal=28,28,20
ForegroundPositive=60,102,89
ForegroundVisited=95,96,68

[Colors:Window]
BackgroundAlternate=252,250,236
BackgroundNormal=252,250,236
DecorationFocus=94,98,27
DecorationHover=94,98,27
ForegroundActive=94,98,27
ForegroundInactive=71,71,59
ForegroundLink=60,102,89
ForegroundNegative=186,26,26
ForegroundNeutral=95,96,68
ForegroundNormal=28,28,20
ForegroundPositive=60,102,89
ForegroundVisited=95,96,68

[WM]
activeBackground=252,250,236
activeBlend=28,28,20
activeForeground=28,28,20
inactiveBackground=252,250,236
inactiveBlend=71,71,59
inactiveForeground=71,71,59
