title Arch Linux Cachyos Bore
linux /vmlinuz-linux-cachyos-bore
initrd  /intel-ucode.img
initrd /booster-linux-cachyos-bore.img
options root=PARTUUID=ec6823d7-e577-4962-9119-85790acd8afa rw modprobe.blacklist=radeon,amdgpu
