# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#1d1b20"

# Title color for boxes
theme[title]="#6750a4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#625b71"

# Background color of selected item in processes box
theme[selected_bg]="#6750a4"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#49454e"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#625b71"

# Cpu box outline color
theme[cpu_box]="#7a757f"

# Memory/disks box outline color
theme[mem_box]="#7a757f"

# Net up/down box outline color
theme[net_box]="#7a757f"

# Processes box outline color
theme[proc_box]="#7a757f"

# Box divider line and small boxes line color
theme[div_line]="#e7e0eb"

# Temperature graph colors
theme[temp_start]="#625b71"
theme[temp_mid]="#6750a4"
theme[temp_end]="#b3261e"

# CPU graph colors
theme[cpu_start]="#625b71"
theme[cpu_mid]="#6750a4"
theme[cpu_end]="#b3261e"

# Mem/Disk free meter
theme[free_start]="#625b71"
theme[free_mid]=""
theme[free_end]="#ece6ee"

# Mem/Disk cached meter
theme[cached_start]="#625b71"
theme[cached_mid]=""
theme[cached_end]="#ece6ee"

# Mem/Disk available meter
theme[available_start]="#6750a4"
theme[available_mid]=""
theme[available_end]="#eaddff"

# Mem/Disk used meter
theme[used_start]="#b3261e"
theme[used_mid]=""
theme[used_end]="#f9dedc"

# Download graph colors
theme[download_start]="#625b71"
theme[download_mid]="#6750a4"
theme[download_end]="#625b71"

# Upload graph colors
theme[upload_start]="#625b71"
theme[upload_mid]="#6750a4"
theme[upload_end]="#625b71"
