# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#000000"

# Title color for boxes
theme[title]="#2c2e00"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#2c2e15"

# Background color of selected item in processes box
theme[selected_bg]="#2c2e00"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#000000"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#033327"

# Cpu box outline color
theme[cpu_box]="#2d2d21"

# Memory/disks box outline color
theme[mem_box]="#2d2d21"

# Net up/down box outline color
theme[net_box]="#2d2d21"

# Processes box outline color
theme[proc_box]="#2d2d21"

# Box divider line and small boxes line color
theme[div_line]="#4a4a3d"

# Temperature graph colors
theme[temp_start]="#2c2e15"
theme[temp_mid]="#2c2e00"
theme[temp_end]="#600004"

# CPU graph colors
theme[cpu_start]="#2c2e15"
theme[cpu_mid]="#2c2e00"
theme[cpu_end]="#600004"

# Mem/Disk free meter
theme[free_start]="#2c2e15"
theme[free_mid]=""
theme[free_end]="#4a4b30"

# Mem/Disk cached meter
theme[cached_start]="#033327"
theme[cached_mid]=""
theme[cached_end]="#265144"

# Mem/Disk available meter
theme[available_start]="#2c2e00"
theme[available_mid]=""
theme[available_end]="#494d04"

# Mem/Disk used meter
theme[used_start]="#600004"
theme[used_mid]=""
theme[used_end]="#98000a"

# Download graph colors
theme[download_start]="#2c2e15"
theme[download_mid]="#2c2e00"
theme[download_end]="#033327"

# Upload graph colors
theme[upload_start]="#2c2e15"
theme[upload_mid]="#2c2e00"
theme[upload_end]="#033327"
