# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#231918"

# Title color for boxes
theme[title]="#904b3e"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#775650"

# Background color of selected item in processes box
theme[selected_bg]="#904b3e"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#534340"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#6f5c2e"

# Cpu box outline color
theme[cpu_box]="#857370"

# Memory/disks box outline color
theme[mem_box]="#857370"

# Net up/down box outline color
theme[net_box]="#857370"

# Processes box outline color
theme[proc_box]="#857370"

# Box divider line and small boxes line color
theme[div_line]="#d8c2be"

# Temperature graph colors
theme[temp_start]="#775650"
theme[temp_mid]="#904b3e"
theme[temp_end]="#ba1a1a"

# CPU graph colors
theme[cpu_start]="#775650"
theme[cpu_mid]="#904b3e"
theme[cpu_end]="#ba1a1a"

# Mem/Disk free meter
theme[free_start]="#775650"
theme[free_mid]=""
theme[free_end]="#ffdad4"

# Mem/Disk cached meter
theme[cached_start]="#6f5c2e"
theme[cached_mid]=""
theme[cached_end]="#fae0a6"

# Mem/Disk available meter
theme[available_start]="#904b3e"
theme[available_mid]=""
theme[available_end]="#ffdad4"

# Mem/Disk used meter
theme[used_start]="#ba1a1a"
theme[used_mid]=""
theme[used_end]="#ffdad6"

# Download graph colors
theme[download_start]="#775650"
theme[download_mid]="#904b3e"
theme[download_end]="#6f5c2e"

# Upload graph colors
theme[upload_start]="#775650"
theme[upload_mid]="#904b3e"
theme[upload_end]="#6f5c2e"
