TERM=foot
PAGER=bat
# MANPAGER=nvim +Man!
# MANPAGER=nvim -u ~/.vimrc +Man!
MANPAGER=vi -M +MANPAGER -

VISUAL=nvim
EDITOR=nvim
BROWSER=firefox
NVIM_APPNAME=lazyvim

# XCURSOR_SIZE=24
# XCURSOR_THEME=Vimix-cursors

# GTK_THEME=Orchis-Light-Compact

# GDK_BACKEND=wayland,x11
# SDL_VIDEODRIVER=wayland
# CLUTTER_BACKEND=wayland

QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=qt5ct
QT_WAYLAND_DISABLE_WINDOWDECORATION=1

QT_IM_MODULE=fcitx
# GTK_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
GLFW_IM_MODULE=ibus

MOZ_ENABLE_WAYLAND=1
LIBVA_DRIVER_NAME=iHD
_JAVA_AWT_WM_NONREPARENTING=1
ELECTRON_OZONE_PLATFORM_HINT=auto

# PATH=%h/.local/bin:%h/.config/emacs/bin:${PATH}
# PATH=${HOME}/.local/bin:${HOME}/.config/emacs/bin:${PATH}
