XCURSOR_SIZE=24
XCURSOR_THEME=Adwaita

GDK_BACKEND=wayland,x11
SDL_VIDEODRIVER=wayland
CLUTTER_BACKEND=wayland

QS_ICON_THEME=Papirus
# QT_STYLE_OVERRIDE=Kvantum
QT_QPA_PLATFORMTHEME=qt6ct
QT_QPA_PLATFORM=wayland;xcb
# QT_WAYLAND_DISABLE_WINDOWDECORATION=1

QT_IM_MODULE=fcitx
# GTK_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
GLFW_IM_MODULE=fcitx

ELECTRON_OZONE_PLATFORM_HINT=wayland
