XCURSOR_SIZE=24
XCURSOR_THEME=Adwaita

XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=niri
XDG_SESSION_DESKTOP=niri

GDK_BACKEND=wayland,x11
SDL_VIDEODRIVER=wayland
CLUTTER_BACKEND=wayland

# QT_STYLE_OVERRIDE=Kvantum
QT_QPA_PLATFORM=wayland;xcb
# QT_QPA_PLATFORMTHEME=qt6ct
# QT_WAYLAND_DISABLE_WINDOWDECORATION=1

QT_IM_MODULE=fcitx
# GTK_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
GLFW_IM_MODULE=fcitx

TERMINAL=footclient
MOZ_ENABLE_WAYLAND=1
# LIBVA_DRIVER_NAME=iHD
_JAVA_AWT_WM_NONREPARENTING=1
ELECTRON_OZONE_PLATFORM_HINT=wayland
APP2UNIT_SLICES=a=app-graphical.slice b=background-graphical.slice s=session-graphical.slice
