MBTN_LEFT cycle pause

SHIFT+RIGHT   playlist-next
SHIFT+LEFT    playlist-prev

SPACE cycle pause; script-message osc-show
RIGHT seek 5 exact; script-message osc-show
LEFT seek -5 exact; script-message osc-show
