cursor #ffffff
cursor_text_color #ffffff

foreground            #ffffff
background            #14140c
selection_foreground  #000000
selection_background  #c8c9a6
url_color             #f1f69e

color0   #14140c
color1   #ff8472
color2   #88f67b
color3   #ffe972
color4   #e3e985
color5   #6d7127
color6   #f1f69e
color7   #feffef
color8   #9f9f93
color9   #ffab9f
color10  #afffa5
color11  #fff1a5
color12  #faffb1
color13  #fbffbf
color14  #fcffd5
color15  #fefff8
